/**
 * Shared LLM client for the brain extension.
 *
 * Provider chain: llama-cpp (local Gemma) → NVIDIA NIM
 *
 * Reads providers from ~/.pi/agent/models.json (generated by NixOS ai-coding-tools module).
 * Handles reasoning models that consume tokens for thinking:
 * - Sends system prompt instructing direct response (no thinking)
 * - Uses high max_tokens (16384+) to leave room for content after reasoning
 * - Falls back through chain on timeout or API failure
 */

import { readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

export interface LLMProvider {
	baseUrl: string;
	apiKey: string;
	model: string;
	name: string;
}

let cachedProviders: LLMProvider[] | null = null;

/** Invalidate cached providers (e.g. after models.json changes) */
export function invalidateProviders(): void {
	cachedProviders = null;
}

/** Provider priority order — local first, cloud fallback, remote local last resort */
const PROVIDER_ORDER = ["llama-cpp", "zai", "nvidia-nim", "sentry"];

export function getProviders(): LLMProvider[] {
	if (cachedProviders) return cachedProviders;
	cachedProviders = [];

	try {
		const models = JSON.parse(
			readFileSync(join(homedir(), ".pi/agent/models.json"), "utf-8"),
		);

		// Build provider chain in priority order
		for (const providerKey of PROVIDER_ORDER) {
			const provider = models.providers?.[providerKey];
			if (!provider) continue;

			// Pick the best model for brain operations (cheap + capable)
			let modelId = provider.models?.[0]?.id || "unknown";

			if (providerKey === "zai") {
				modelId =
					provider.models?.find((m: any) => m.id === "glm-5-turbo")?.id ||
					modelId;
			} else if (providerKey === "nvidia-nim") {
				// Strip the "nvidia-nim/" prefix that models.json adds for namespacing
				// — NVIDIA API expects bare model IDs (e.g. "deepseek-ai/deepseek-v3.1")
				modelId = modelId.replace(/^nvidia-nim\//, "");
			} else if (providerKey === "llama-cpp") {
				// Hardcode E4B — models.json is generated by NixOS and may be stale
				modelId = "gemma-4-e4b-it";
			}

			let baseUrl = provider.baseUrl;
			if (providerKey === "llama-cpp") {
				// models.json points to sentry:1235 (often down); use local llama.cpp
				// which the gateway confirms is healthy on localhost:1235
				baseUrl = "http://localhost:1235/v1";
			}

			cachedProviders.push({
				baseUrl,
				apiKey: provider.apiKey || "unused",
				model: modelId,
				name: providerKey,
			});
		}

		if (cachedProviders.length === 0) {
			console.error("[brain] WARNING: No providers found in models.json");
		}

		// Sentry fallback — Gemma E2B on sentry (10.1.1.140:1235)
		// Not in models.json (NixOS-generated), so add statically
		cachedProviders.push({
			baseUrl: "http://10.1.1.140:1235/v1",
			apiKey: "unused",
			model: "gemma-4-e2b-it",
			name: "sentry",
		});
	} catch (err: any) {
		console.error(`[brain] ERROR reading models.json: ${err.message}`);
	}

	return cachedProviders;
}

/** Task complexity tier for model routing. */
export type Tier = "fast" | "quality" | "verify";

const TIER_ORDER: Record<Tier, string[]> = {
	// Fast: E2B on sentry → ZAI (for extraction, relevance, simple JSON)
	fast: ["sentry", "zai", "llama-cpp", "nvidia-nim"],
	// Quality: E4B on zephyr → ZAI → NIM (for synthesis, compilation)
	quality: ["llama-cpp", "zai", "nvidia-nim", "sentry"],
	// Verify: Cloud models only (for quality gates)
	verify: ["nvidia-nim", "zai", "llama-cpp", "sentry"],
};

/**
 * Call an LLM with tiered routing and automatic fallback.
 *
 * Tier routing:
 * - "fast": E2B (sentry) first — extraction, relevance, small JSON output
 * - "quality": E4B (zephyr) first — synthesis, compilation, complex output
 * - "verify": Cloud NIM first — quality gates for critical output
 *
 * Instructs models to respond directly without thinking for structured output.
 */
export async function callLLM(
	prompt: string,
	maxTokens = 16384,
	signal?: AbortSignal,
	systemPrompt?: string,
	tier: Tier = "quality",
): Promise<string> {
	const allProviders = getProviders();
	if (allProviders.length === 0) throw new Error("No LLM providers configured");

	// Order providers by tier
	const tierOrder = TIER_ORDER[tier];
	const providersByName = new Map(allProviders.map((p) => [p.name, p]));
	const providers = tierOrder
		.map((name) => providersByName.get(name))
		.filter((p): p is LLMProvider => p !== undefined);

	// Try each provider in tier order
	for (let i = 0; i < providers.length; i++) {
		const provider = providers[i];
		const isLast = i === providers.length - 1;

		try {
			return await callProvider(
				provider,
				prompt,
				maxTokens,
				signal,
				systemPrompt,
			);
		} catch (err: any) {
			const msg = err?.message || String(err);
			console.error(
				`[brain] ${provider.name} (${tier}) failed: ${msg}${isLast ? "" : ", trying fallback..."}`,
			);
			if (isLast) throw err;
		}
	}

	throw new Error("All providers failed");
}

async function callProvider(
	provider: LLMProvider,
	prompt: string,
	maxTokens: number,
	signal?: AbortSignal,
	systemPrompt?: string,
): Promise<string> {
	const messages: any[] = [];

	if (systemPrompt) {
		messages.push({ role: "system", content: systemPrompt });
	} else {
		// Default: instruct direct response to suppress reasoning overhead
		messages.push({
			role: "system",
			content:
				"Do not think. Respond directly with the requested output format. No preamble, no explanation.",
		});
	}

	messages.push({ role: "user", content: prompt });

	const response = await fetch(`${provider.baseUrl}/chat/completions`, {
		method: "POST",
		headers: {
			Authorization: `Bearer ${provider.apiKey}`,
			"Content-Type": "application/json",
		},
		body: JSON.stringify({
			model: provider.model,
			messages,
			max_tokens: maxTokens,
		}),
		signal,
	});

	if (!response.ok) {
		throw new Error(`LLM API error (${provider.name}): ${response.status}`);
	}

	const data = await response.json();
	const choice = data.choices?.[0];
	const message = choice?.message;
	if (!message) return "";

	// Some reasoning models (GLM-5) put the actual response in reasoning_content
	// and leave content empty. Fall back to reasoning_content when content is blank.
	const rawContent = (message.content || "").trim();
	const reasoningContent = (message.reasoning_content || "").trim();
	const content = rawContent || reasoningContent;

	// If truncated, throw so caller can retry with different params
	if (!content && choice.finish_reason === "length") {
		throw new Error(
			`${provider.name}: response truncated (finish_reason=length)`,
		);
	}

	return content;
}

// Backward compat
export function getZAIConfig() {
	const providers = getProviders();
	return providers.find((p) => p.name === "zai") || null;
}

export async function callZAI(
	prompt: string,
	maxTokens = 16384,
	signal?: AbortSignal,
): Promise<string> {
	return callLLM(prompt, maxTokens, signal);
}
